1. Introduction to tensors
2. Gettings information from tensors
3. Manipulating tensors
4. Tensors & Numpy
5. Using @tf.function
6. Using GPUs with Tensorflow

## Introduction to Tensors
* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2-dim array of numbers
* Tensor: an n-dim array of numbers (n can be any number)

In [1]:
# import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [3]:
 # create tensors with tf.constant()
 scalar = tf.constant(7)
 scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check the number of dimensions of a tensor
scalar.ndim

0

In [5]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check the dimension of our vector
vector.ndim

1

In [8]:
# create a matrix
matrix = tf.constant([[10, 7], 
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [11]:
# specify the data type with dtype parameter
another_matrix = tf.constant([[10., 7.], 
                              [3., 2.], 
                              [8., 9.]], dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [15]:
# create a tensor
tensor = tf.constant([[[1,2,3,], 
                       [3, 4, 5]], 
                      [[7, 8, 9], 
                       [10, 11, 12]],
                      [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [16]:
tensor.ndim

3

## Creating tensors w/ `tf.Variable`

In [17]:
# create the same tensor with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [20]:
# change one of the elements by .assign()  
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## Creating random tensors


In [24]:
# create two random tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3, 2))

# are they equal?
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the orer of elements in a tensor

If we want shaffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed.


In [28]:
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [53]:
tf.random.set_seed(33) # gloabal level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [52]:
tf.random.shuffle(not_shuffled, seed=33)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

### Other ways to make tensors

In [55]:
# create a tensor of all ones
tf.ones([3, 2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [56]:
# create a tensor of all zeros
tf.zeros(shape=(3, 5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [62]:
# turn Numpy arrays into tensors
# the main difference between Numpy arrays and Tensorflow tensors is that tensors can be run on a GPU.
import numpy as np
numpy_1 = np.arange(1, 10, dtype=np.int32)
numpy_1

# X = tf.constant(some_matrix) 
# y = tf.constant(vector)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [64]:
tensor_1 = tf.constant(numpy_1, shape=(3,3))
tensor_1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [67]:
tensor_2 = tf.constant(numpy_1, shape=(9,1))
tensor_2

<tf.Tensor: shape=(9, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]], dtype=int32)>

### Getting information from tensors

* Shape
* Rank
* Axis or dimension
* Size

In [68]:
# Create a rank 4 tensor (4 dim)
rank4tensor = tf.zeros(shape=[2,3,4,5])
rank4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [69]:
rank4tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [71]:
rank4tensor.shape, rank4tensor.ndim, tf.size(rank4tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [72]:
2*3*4*5

120

In [78]:
print('Datatype of every elments:', rank4tensor.dtype)
print('Number of dimensions (ranks):', rank4tensor.ndim)
print('Shape of tensor:', rank4tensor.shape)
print('Elements along the 0 axis:', rank4tensor.shape[0])
print('Elements along the last axis:', rank4tensor.shape[-1])
print('Total number of elements in tensor:', tf.size(rank4tensor))
print('Total number of elements in tensor (numpy):', tf.size(rank4tensor).numpy())

Datatype of every elments: <dtype: 'float32'>
Number of dimensions (ranks): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in tensor (numpy): 120


### Indexing tensors

In [79]:
# Get the first 2 elements of each dimension
rank4tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [82]:
# rank4tensor shape is (2, 3, 4, 5)
# Get the first element from each dimension from each index except for the second last one
rank4tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [83]:
rank4tensor[:, :1, :, :1]

<tf.Tensor: shape=(2, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [84]:
# create a rank 2 tensor (2 dimensions)
rank2tensr = tf.constant([[1, 2], [3, 4]])
print('Datatype of every elments:', rank2tensr.dtype)
print('Number of dimensions (ranks):', rank2tensr.ndim)
print('Shape of tensor:', rank2tensr.shape)
print('Elements along the 0 axis:', rank2tensr.shape[0])
print('Elements along the last axis:', rank2tensr.shape[-1])
print('Total number of elements in tensor:', tf.size(rank2tensr))
print('Total number of elements in tensor (numpy):', tf.size(rank2tensr).numpy())

Datatype of every elments: <dtype: 'int32'>
Number of dimensions (ranks): 2
Shape of tensor: (2, 2)
Elements along the 0 axis: 2
Elements along the last axis: 2
Total number of elements in tensor: tf.Tensor(4, shape=(), dtype=int32)
Total number of elements in tensor (numpy): 4


In [85]:
 rank2tensr[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [91]:
# insert another dimension
rank3tensor = rank2tensr[:, :, tf.newaxis]
rank3tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [93]:
# alternative to tf.newaxis
tf.expand_dims(rank2tensr, axis=-1) # '-1' means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [94]:
# Expand the 0-axis
tf.expand_dims(rank2tensr, axis=0) # '0' means expand the first axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulating tensors

In [95]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [96]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [98]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [99]:
# Substraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [100]:
# use tensorflow builti-in function

tf.multiply(tensor, 19)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 38],
       [57, 76]], dtype=int32)>

### Matrix multiplicaton

To multiply a matrix by another matrix we need to do the `dot product` of rows and columns. \
The `dot product` is where we multiply matching members, then sum up.

In [101]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [102]:
# Matrix multiplication with python operator '@'
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [103]:
# elements-wise
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [104]:
tensor.shape

TensorShape([2, 2])

In [105]:
# create a tensor (3, 2)
X = tf.constant([[1, 2], [3, 4], [5, 6]])

# create a tensor (3, 2)
Y = tf.constant([[7, 8], [9, 10], [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [109]:
# The inner dimensions must match
# The resulting matrix has the shape of the outer dimensions

# change the shape of Y
Y = tf.reshape(Y, shape=(2, 3))
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [111]:
tf.matmul(X, Y) # X@Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [115]:
# Can do the same with Transpose
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

**The dot product**

Perform matrix multiplication using: `tf.matmul()` or `tf.tensordot()`.


In [117]:
# create a tensor (3, 2)
X = tf.constant([[1, 2], [3, 4], [5, 6]])

# create a tensor (3, 2)
Y = tf.constant([[7, 8], [9, 10], [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [118]:
tf.tensordot(
    tf.transpose(X), Y, axes=1
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [121]:
tf.matmul(
    X, tf.transpose(Y)
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [123]:
tf.matmul(
    X, tf.reshape(Y, shape=(2, 3))
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [125]:
print('Normal Y:')
print(Y)
print('\nY Reshape to (2, 3):')
print(tf.reshape(Y, shape=(2, 3)))
print('\nY Transposed:')
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)

Y Reshape to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)

Y Transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [127]:
# When performing matrix multiplication on two tensors and one axes doesn't line up,
# you will transpose (rather than reshape) of the tensors.
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

### Changing the datatype of a tensor

In [130]:
a = tf.constant([1.7, 2.4])
a.dtype

tf.float32

In [131]:
b = tf.constant([8, 2])
b.dtype

tf.int32

In [134]:
# change from float32 to float16 (reduce precision)
c = tf.cast(a, dtype=tf.float16)
c, c.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 2.4], dtype=float16)>,
 tf.float16)

In [136]:
# change from int32 to float32 
e = tf.cast(b, dtype=tf.float32)
e, e.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8., 2.], dtype=float32)>,
 tf.float32)

### Aggregating tensors

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor


In [137]:
d = tf.constant([-2, -3])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -3], dtype=int32)>

In [138]:
# Get the absolute values
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [140]:
  # Create a random tensor
  e = tf.constant(np.random.randint(0, 100, size=50))
  e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([44, 70, 66, 37,  5, 52, 43, 71, 13, 75, 13, 40, 95,  9, 96, 34, 19,
       93, 18,  7, 31, 45, 44, 86, 55, 54, 57,  3, 33,  2, 73, 71, 96, 26,
       22,  3,  0, 57, 88, 41, 69, 47, 86, 46, 96, 65,  4, 26, 54, 33])>

In [141]:
tf.size(e), e.shape, e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [142]:
# find the minimum
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [143]:
# find the maxmum
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [144]:
# find the mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [145]:
# find the sum
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2313>

In [147]:
# find the variance
import tensorflow_probability as tfp
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=845>

In [153]:
tf.math.reduce_variance(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=845.27234>

In [151]:
# find the standard deviation
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.073568>

## Find the positional maximum and minimum

In [156]:
# create a new tensor

tf.random.set_seed(32)
f = tf.random.uniform(shape=[10])
f

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.54520595, 0.13372338, 0.45232666, 0.15582252, 0.9621073 ,
       0.8151462 , 0.4068215 , 0.9565903 , 0.5532354 , 0.44936454],
      dtype=float32)>

In [157]:
# find the positional maximum
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [158]:
# index on largest value position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9621073>

In [159]:
# find the max value
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9621073>

In [160]:
# find the positional minimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [163]:
# index on minimum value position
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.13372338>

In [162]:
# find the min value
tf.reduce_min(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.13372338>

### Squeezing a tensor (removing all single dimensions)

In [166]:
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [167]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [170]:
g_squeezed = tf.squeeze(g)
g_squeezed.shape 

TensorShape([50])

### One-Hot encoding tensors

In [171]:
# create a list of indices
some_list = [0, 1, 2, 3]

# one hot encode list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [174]:
# custom values for one-hot encoding
tf.one_hot(some_list, depth=4, on_value='joy', off_value='cool')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'joy', b'cool', b'cool', b'cool'],
       [b'cool', b'joy', b'cool', b'cool'],
       [b'cool', b'cool', b'joy', b'cool'],
       [b'cool', b'cool', b'cool', b'joy']], dtype=object)>

### Squaring, log, square root

In [175]:
# create a new tensor
h = tf.range(1, 10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [176]:
# square
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [177]:
# find the squareroot (requires non-int type)
tf.math.sqrt(tf.cast(h, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [179]:
# find the log (requires non-int type)
tf.math.log(tf.cast(h, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

In [180]:
# create a tensor directly from numpy array
j = tf.constant(np.array([1., 2., 3.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [182]:
# convert tensor back to numpy array
np.array(j), type(np.array(j))

(array([1., 2., 3.]), numpy.ndarray)

In [183]:
j.numpy(), type(j.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [184]:
j = tf.constant([3.])
j.numpy()[0]

3.0

In [186]:
numpy_j = tf.constant(np.array([3., 4., 5.]))
tensor_j = tf.constant([3., 4., 5.])

# check the datatype of each
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)

# Accessing GPU

If you hace access to a CUDA-enabled GPU, Tensorflow will automatically use it whenever possible.

In [3]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
!nvidia-smi

Thu Aug 12 11:05:34 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8    28W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------