## Pytorch Fundamentals

* Introduction to tensors
* Gettings information from tensors
* Manipulating tensors
* Accessing GPU

## Introduction to tensors
* Scalar: a single number
* Vector: a number with direction
* Matrix: a `2-dim` array of numbers
* Tensor: an `n-dim` array of number 


In [1]:
import torch
print(torch.__version__)

1.9.0+cu102


In [2]:
# create tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# check the number of dimensions of a tensor
scalar.dim()

0

In [4]:
# create a vector
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [5]:
vector.dim()

1

In [6]:
# create a matrix
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [7]:
matrix.dim()

2

In [8]:
# create a tensor
tensor = torch.tensor([
        [[1,2,3], [4,5,6]], 
        [[7, 8, 9], [10, 11, 12]], 
        [[13, 14, 15], [16, 17, 18]]
    ])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])

In [9]:
tensor.dim()

3

### Creating random tensors

In [10]:
torch.rand(3)

tensor([0.4393, 0.7593, 0.6309])

In [11]:
torch.rand(2,3)

tensor([[0.3862, 0.2751, 0.7491],
        [0.6913, 0.0362, 0.6515]])

In [12]:
torch.randint(1, 10, (4,))

tensor([9, 3, 4, 2])

In [13]:
torch.randint(1, 3, (2, 4))

tensor([[1, 2, 1, 2],
        [2, 1, 2, 1]])

### Other ways to make tensors

In [14]:
# create a tensor of all ones
torch.ones((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
# create a tensor of all zeros
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Gettings information from tensors

* Shape
* Rank
* Axis or Dimension
* Number of elements 

In [16]:
# create a rank 4 tensor (4 dim)
rank_4_tensor = torch.zeros([2, 3, 4, 5])
rank_4_tensor

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])

In [17]:
rank_4_tensor[0]

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [18]:
rank_4_tensor.shape, rank_4_tensor.dim(), torch.numel(rank_4_tensor)

(torch.Size([2, 3, 4, 5]), 4, 120)

In [19]:
# number of elements
2*3*4*5

120

In [20]:
print('Datatype of every elments:', rank_4_tensor.dtype)
print('Number of dimensions (ranks):', rank_4_tensor.dim())
print('Shape of tensor:', rank_4_tensor.shape)
print('Elements along the 0 axis:', rank_4_tensor.shape[0])
print('Elements along the last axis:', rank_4_tensor.shape[-1])
print('Total number of elements in tensor:', torch.numel(rank_4_tensor))

Datatype of every elments: torch.float32
Number of dimensions (ranks): 4
Shape of tensor: torch.Size([2, 3, 4, 5])
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in tensor: 120


In [21]:
# rank_4_tensor shape is (2, 3, 4, 5)
# Get the first element from each dimension from each index except for the second last one
rank_4_tensor[:1, :1, :, :1], rank_4_tensor[:1, :1, :, :1].shape

(tensor([[[[0.],
           [0.],
           [0.],
           [0.]]]]), torch.Size([1, 1, 4, 1]))

In [22]:
rank_4_tensor[:, :1, :, :1], rank_4_tensor[:, :1, :, :1].shape

(tensor([[[[0.],
           [0.],
           [0.],
           [0.]]],
 
 
         [[[0.],
           [0.],
           [0.],
           [0.]]]]), torch.Size([2, 1, 4, 1]))

In [23]:
# create a rank 2 tensor (2 dimensions)
rank_2_tensor = torch.tensor([[1., 2.], [3., 4.]])
print('Datatype of every elments:', rank_2_tensor.dtype)
print('Number of dimensions (ranks):', rank_2_tensor.dim())
print('Shape of tensor:', rank_2_tensor.shape)
print('Elements along the 0 axis:', rank_2_tensor.shape[0])
print('Elements along the last axis:', rank_2_tensor.shape[-1])
print('Total number of elements in tensor:', torch.numel(rank_2_tensor))

Datatype of every elments: torch.float32
Number of dimensions (ranks): 2
Shape of tensor: torch.Size([2, 2])
Elements along the 0 axis: 2
Elements along the last axis: 2
Total number of elements in tensor: 4


In [24]:
# insert another dimension
rank_3_tensor = rank_2_tensor.unsqueeze(2)
rank_3_tensor.shape

torch.Size([2, 2, 1])

In [25]:
# insert another dimension
rank_3_tensor = rank_2_tensor.unsqueeze(1)
rank_3_tensor.shape

torch.Size([2, 1, 2])

## Manipulating tensors

### Manipulationg tensors

In [26]:
tensor = torch.tensor([[1, 2], [3, 4]])
tensor + 10

tensor([[11, 12],
        [13, 14]])

In [27]:
# multiplication
tensor * 10

tensor([[10, 20],
        [30, 40]])

In [28]:
# substraction
tensor - 10

tensor([[-9, -8],
        [-7, -6]])

In [29]:
# use pytorch built-in function
torch.multiply(tensor, 10)

tensor([[10, 20],
        [30, 40]])

### Matrix muliplication

* To multiply a matrix by another matrix we need to do the dot product of rows and columns. 

* The `dot product` is where we multiply matching members, then sum up.

In [30]:
print(tensor)
torch.matmul(tensor, tensor)

tensor([[1, 2],
        [3, 4]])


tensor([[ 7, 10],
        [15, 22]])

In [31]:
# Matrix multiplication with python operator '@'
tensor@tensor

tensor([[ 7, 10],
        [15, 22]])

In [32]:
# elements-wise
tensor*tensor

tensor([[ 1,  4],
        [ 9, 16]])

In [33]:
# create a tensor (3, 2)
X = torch.tensor([[1, 2], [3, 4], [5, 6]])
# create a tensor (3, 2)
Y = torch.tensor([[7, 8], [9, 10], [11, 12]])

print(X)
print(Y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])


In [34]:
# The inner dimensions must match
# The resulting matrix has the shape of the outer dimensions

# change the shape of Y
Y = torch.reshape(Y, shape=(2, 3))
Y

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [35]:
torch.matmul(X, Y) # X@Y 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [36]:
# Can do the same with Transpose
print('Normal X:')
print(X)
print('\n X Transpose:')
print(torch.transpose(X, 0, 1)) 
print('\n X Reshape:')
print(torch.reshape(X, shape=(2, 3)))

Normal X:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

 X Transpose:
tensor([[1, 3, 5],
        [2, 4, 6]])

 X Reshape:
tensor([[1, 2, 3],
        [4, 5, 6]])


### Change the datatype of a tensor

* Tensors Data Types: [documentation](https://pytorch.org/docs/stable/tensors.html)

In [37]:
a = torch.tensor([1., 2., 3])
a.dtype

torch.float32

In [38]:
b = torch.tensor([1, 2, 3])
b.dtype

torch.int64

In [39]:
c = b.type(torch.float)
c.dtype

torch.float32

In [40]:
d = a.type(torch.DoubleTensor)
d.dtype

torch.float64

### Aggregating tensors
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [41]:
# get the absolute value
e = torch.tensor([-1, 3])
torch.abs(e)

tensor([1, 3])

In [42]:
# create a random tensor
f = torch.rand(100)
f

tensor([0.0776, 0.4305, 0.8195, 0.2455, 0.7735, 0.6219, 0.6253, 0.5796, 0.9274,
        0.3596, 0.7649, 0.7620, 0.0201, 0.8284, 0.3166, 0.4267, 0.9441, 0.0922,
        0.6559, 0.8529, 0.1500, 0.8529, 0.0648, 0.2681, 0.6131, 0.1848, 0.1933,
        0.8777, 0.6893, 0.2795, 0.6192, 0.1719, 0.9803, 0.5507, 0.0515, 0.7943,
        0.8546, 0.7183, 0.1477, 0.9981, 0.6084, 0.7001, 0.3427, 0.2716, 0.7047,
        0.2891, 0.5002, 0.0801, 0.5686, 0.7307, 0.3149, 0.4853, 0.1133, 0.4749,
        0.3254, 0.9352, 0.2291, 0.9761, 0.1172, 0.6944, 0.7084, 0.4890, 0.0896,
        0.3595, 0.9687, 0.5376, 0.2749, 0.0829, 0.1402, 0.1029, 0.8064, 0.1923,
        0.4340, 0.1157, 0.9513, 0.2106, 0.2195, 0.0050, 0.9580, 0.6767, 0.2645,
        0.5570, 0.2807, 0.5375, 0.8863, 0.8148, 0.5917, 0.1290, 0.2873, 0.6444,
        0.3012, 0.4107, 0.6593, 0.5075, 0.6961, 0.9259, 0.1948, 0.8967, 0.8547,
        0.0440])

In [43]:
# find the minimum
torch.min(f)

tensor(0.0050)

In [44]:
# find the maxmum
torch.max(f)

tensor(0.9981)

In [45]:
# find the sum
torch.sum(f)

tensor(49.4540)

In [46]:
# find the mean
torch.mean(f)

tensor(0.4945)

In [47]:
# find the variance
torch.var(f)

tensor(0.0883)

In [48]:
# find the standard deviation
torch.std(f)

tensor(0.2972)

### Find the positional maximum and minimum

In [49]:
g = torch.rand(20)
g

tensor([0.0338, 0.3642, 0.6661, 0.4835, 0.8575, 0.8229, 0.1264, 0.9617, 0.2639,
        0.0601, 0.6706, 0.7436, 0.6592, 0.6216, 0.2151, 0.3886, 0.4736, 0.0097,
        0.2490, 0.8923])

In [50]:
# Returns the indices of the maximum value of all elements in the input tensor.
torch.argmax(g), torch.max(g)

(tensor(7), tensor(0.9617))

In [51]:
torch.argmin(g), torch.min(g)

(tensor(17), tensor(0.0097))

### One-Hot encoding tensors

* `num_classes`: Total number of classes. If set to `-1`, the number of classes will be inferred as one greater than the largest class value in the input tensor.

In [52]:
from torch.nn import functional as F

In [53]:
tensor = torch.tensor([0, 1, 2, 3])

# one hot encode 
F.one_hot(tensor, num_classes=4)

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [54]:
tensor = torch.tensor([3, 4, 5])

# one hot encode
F.one_hot(tensor)

tensor([[0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1]])

### Tensors & Numpy

In [55]:
import numpy as np

In [56]:
j = torch.tensor([1,2,3,4])
j

tensor([1, 2, 3, 4])

In [57]:
np.array(j), type(np.array(j))

(array([1, 2, 3, 4]), numpy.ndarray)

In [58]:
j.numpy(), type(j.numpy())

(array([1, 2, 3, 4]), numpy.ndarray)

In [59]:
j.numpy()[0]

1

In [60]:
numpy_k = np.array([2., 3., 4.])
numpy_k, numpy_k.dtype, type(numpy_k)

(array([2., 3., 4.]), dtype('float64'), numpy.ndarray)

In [61]:
tensor_k = torch.tensor(numpy_k)
tensor_k, tensor_k.dtype, type(tensor_k)

(tensor([2., 3., 4.], dtype=torch.float64), torch.float64, torch.Tensor)

## Accessing GPU

In [62]:
!nvidia-smi

Wed Aug 25 12:39:35 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8    27W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [63]:
# check if cuda is available 
torch.cuda.is_available()

True

In [64]:
# GPU name
torch.cuda.get_device_name()

'Tesla K80'

In [65]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

device

device(type='cuda')

(In Pytorch) Tensors can either be on the CPU or GPU. You can check that with the following:

In [66]:
s = torch.tensor([2., 3., 4., 5.])
s.is_cuda

False

In [67]:
# torch.Tensor.to: Performs Tensor dtype and/or device conversion. 
s.to(device).is_cuda

True