## Matrices Basic

In [1]:
import numpy as np
import torch

### Creating Matrices

In [2]:
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
# convert to numpy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
# convert to pytorch tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

### Creating Matrices with Default Values

In [5]:
# numpy
np.ones([2, 2]) # 2x2

array([[1., 1.],
       [1., 1.]])

In [6]:
# pytorch
torch.ones([2, 2]) # 2x2

tensor([[1., 1.],
        [1., 1.]])

In [7]:
# numpy random
np.random.rand(2, 2)

array([[0.88978181, 0.93160704],
       [0.2076579 , 0.53900701]])

In [8]:
# torch random
torch.rand(2, 2)

tensor([[0.5994, 0.2954],
        [0.7659, 0.2889]])

### Seed for Reproducibility

In [9]:
# seed for GPU is different
if torch.cuda.is_available():
    print('GPU available')
    torch.cuda.manual_seed_all(0)

In [10]:
# numpy seed 
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [11]:
# random values are same if seed same
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [12]:
# no seed
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [13]:
# no seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [14]:
# pytorch seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [15]:
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [16]:
torch.rand(2, 2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

### Numpy to Torch

In [17]:
np_arr = np.ones((2, 2))
print(np_arr, type(np_arr))

[[1. 1.]
 [1. 1.]] <class 'numpy.ndarray'>


In [18]:
# convert to Torch tensor
torch_tensor = torch.from_numpy(np_arr)
print(torch_tensor, type(torch_tensor))

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64) <class 'torch.Tensor'>


### The conversion suports:
1. double
2. float
3. int64, int32, uint8

|Numpy Array Type|  Torch Tensor Type|
|---|---|
|   int64|   LongTensor|
|   int32|   IntegerTensor|
|   uint8|   ByteTensor|
|   float64|   DoubleTensor|
|   float32|   FloatTensor|
|   double|   DoubleTensor|

In [19]:
# int32
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [20]:
# int64
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]])

In [21]:
# uint8
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [22]:
# float64
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [23]:
# float32
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]])

In [24]:
# double
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

### Torch to Numpy

In [25]:
torch_tensor = torch.ones(2, 2)
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray