In [ ]:
import torch

In [ ]:
z = torch.Tensor(4, 5)
z

tensor([[-2.2265e+30,  3.0878e-41,  7.0065e-44,  6.8664e-44,  6.3058e-44],
        [ 6.7262e-44,  7.1466e-44,  6.3058e-44,  6.7262e-44,  7.2868e-44],
        [ 1.1771e-43,  6.8664e-44,  6.8664e-44,  8.1275e-44,  7.2868e-44],
        [ 7.8473e-44,  8.1275e-44,  7.0065e-44,  7.5670e-44,  6.4460e-44]])

In [ ]:
z.dtype

torch.float32

In [ ]:
a = torch.FloatTensor(4, 5)
b = torch.FloatTensor([[2, 4], [3, 5]])

In [ ]:
a

tensor([[-1.3108e+31,  3.0878e-41,  7.0065e-44,  6.8664e-44,  6.3058e-44],
        [ 6.7262e-44,  7.1466e-44,  6.3058e-44,  6.7262e-44,  7.2868e-44],
        [ 1.1771e-43,  6.8664e-44,  6.8664e-44,  8.1275e-44,  7.2868e-44],
        [ 7.9874e-44,  8.1275e-44,  7.2868e-44,  7.2868e-44,  6.4460e-44]])

In [ ]:
b

tensor([[2., 4.],
        [3., 5.]])

In [ ]:
a.dtype

torch.float32

In [ ]:
b.dtype

torch.float32

In [ ]:
a = torch.IntTensor(4, 5)
b = torch.IntTensor([[2, 4], [3, 5]])

(tensor([[-236923008,      22035,         50,         49,         45],
         [        48,         51,         45,         48,         52],
         [        84,         49,         49,         58,         52],
         [        56,         58,         50,         54,         46]],
        dtype=torch.int32), tensor([[2, 4],
         [3, 5]], dtype=torch.int32))

In [ ]:
a

tensor([[-1.3108e+31,  3.0878e-41,  7.0065e-44,  6.8664e-44,  6.3058e-44],
        [ 6.7262e-44,  7.1466e-44,  6.3058e-44,  6.7262e-44,  7.2868e-44],
        [ 1.1771e-43,  6.8664e-44,  6.8664e-44,  8.1275e-44,  7.2868e-44],
        [ 7.9874e-44,  8.1275e-44,  7.2868e-44,  7.2868e-44,  6.4460e-44]])

In [ ]:
b

tensor([[2., 4.],
        [3., 5.]])

In [ ]:
y = a + z
y

tensor([[-1.5335e+31,  6.1755e-41,  1.4013e-43,  1.3733e-43,  1.2612e-43],
        [ 1.3452e-43,  1.4293e-43,  1.2612e-43,  1.3452e-43,  1.4574e-43],
        [ 2.3542e-43,  1.3733e-43,  1.3733e-43,  1.6255e-43,  1.4574e-43],
        [ 1.5835e-43,  1.6255e-43,  1.4293e-43,  1.4854e-43,  1.2892e-43]])

In [ ]:
y.dtype

torch.float32

In [ ]:
torch.add(a, z)

tensor([[-1.5335e+31,  6.1755e-41,  1.4013e-43,  1.3733e-43,  1.2612e-43],
        [ 1.3452e-43,  1.4293e-43,  1.2612e-43,  1.3452e-43,  1.4574e-43],
        [ 2.3542e-43,  1.3733e-43,  1.3733e-43,  1.6255e-43,  1.4574e-43],
        [ 1.5835e-43,  1.6255e-43,  1.4293e-43,  1.4854e-43,  1.2892e-43]])

In [ ]:
a = torch.rand(4, 5)
a

tensor([[0.5662, 0.3340, 0.3637, 0.6589, 0.4047],
        [0.7796, 0.6923, 0.3761, 0.2988, 0.8019],
        [0.0608, 0.7104, 0.2265, 0.2430, 0.0540],
        [0.4433, 0.9275, 0.1360, 0.1504, 0.3233]])

In [ ]:
a.dtype

torch.float32

In [ ]:
b = a.numpy()
b

array([[0.5662462 , 0.33399266, 0.3636843 , 0.6588772 , 0.40472096],
       [0.7795508 , 0.69228077, 0.37605894, 0.29876608, 0.8018946 ],
       [0.06076509, 0.7104141 , 0.22653908, 0.24303794, 0.05397725],
       [0.44328988, 0.9275205 , 0.13598108, 0.1504373 , 0.3233266 ]],
      dtype=float32)

In [ ]:
import numpy as np

In [ ]:
a = np.ones(5)
b = torch.from_numpy(a)

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [ ]:
a

tensor([[0.5662, 0.3340, 0.3637, 0.6589, 0.4047],
        [0.7796, 0.6923, 0.3761, 0.2988, 0.8019],
        [0.0608, 0.7104, 0.2265, 0.2430, 0.0540],
        [0.4433, 0.9275, 0.1360, 0.1504, 0.3233]])

In [ ]:
b

array([[0.5662462 , 0.33399266, 0.3636843 , 0.6588772 , 0.40472096],
       [0.7795508 , 0.69228077, 0.37605894, 0.29876608, 0.8018946 ],
       [0.06076509, 0.7104141 , 0.22653908, 0.24303794, 0.05397725],
       [0.44328988, 0.9275205 , 0.13598108, 0.1504373 , 0.3233266 ]],
      dtype=float32)

TypeError: ignored

In [ ]:
a

In [ ]:
c = b + torch.FloatTensor([1,2,3,4,5])
c.dtype

torch.float64

In [ ]:
c = c.float()
c.dtype

torch.float32

In [ ]:
c = c.double()
c.dtype

torch.float64

In [ ]:
c = c.int()
c.dtype

torch.int32

In [ ]:
x = torch.zeros([2, 1, 2, 1, 2])
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [ ]:
y = torch.squeeze(x)
y.size(), y

(torch.Size([2, 2, 2]), tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]))

In [ ]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(y, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [ ]:
y = torch.squeeze(y, 2)
y.size()

torch.Size([2, 2, 2])

In [ ]:
torch.abs(torch.FloatTensor([-1, -2, 3]))

tensor([1., 2., 3.])

In [ ]:
a = torch.randn(4)
a

tensor([-0.3870, -0.7763, -2.4466,  1.4560])

In [ ]:
b = torch.add(a, 20)
b

tensor([19.6130, 19.2237, 17.5534, 21.4560])

In [ ]:
c = torch.mul(a, 0.1)
c

tensor([-0.0387, -0.0776, -0.2447,  0.1456])

In [ ]:
d = torch.mul(a, b)
d

tensor([ -7.5900, -14.9237, -42.9465,  31.2395])

In [ ]:
x = torch.rand(2, 3)
y = torch.rand(3, 2)
x, y

(tensor([[0.0302, 0.7010, 0.4771],
         [0.0294, 0.2630, 0.0467]]), tensor([[0.9685, 0.7876],
         [0.8229, 0.5334],
         [0.2337, 0.1866]]))

In [ ]:
d = torch.matmul(x, y)
d

tensor([[0.7176, 0.4867],
        [0.2558, 0.1721]])

In [ ]:
d = torch.matmul(y, x)
d

tensor([[0.0524, 0.8861, 0.4989],
        [0.0405, 0.7171, 0.4175],
        [0.0125, 0.2129, 0.1202]])

In [ ]:
y.size()

torch.Size([3, 2])

In [ ]:
y.mean()

tensor(0.5888)

In [ ]:
k = y.mean()
k.data.dtype

torch.float32

In [ ]:
torch.mean(y)

tensor(0.5888)

In [ ]:
torch.mean(y, 0)

tensor([0.6750, 0.5025])

In [ ]:
torch.mean(y, 1)

tensor([0.8780, 0.6781, 0.2101])

In [ ]:
y

tensor([[0.9685, 0.7876],
        [0.8229, 0.5334],
        [0.2337, 0.1866]])

In [ ]:
x = torch.Tensor([
  [1, 2],
  [3, 4],
])

y = torch.Tensor([
  [1, 1],
  [4, 4]
])

x, y

(tensor([[1., 2.],
         [3., 4.]]), tensor([[1., 1.],
         [4., 4.]]))

In [ ]:
torch.eq(x, y)

tensor([[ True, False],
        [False,  True]])

In [ ]:
torch.equal(y, y)

True

In [ ]:
torch.ge(x, y)

tensor([[ True,  True],
        [False,  True]])

In [ ]:
torch.le(x, y)

tensor([[ True, False],
        [ True,  True]])

In [ ]:
torch.gt(x, y)

tensor([[False,  True],
        [False, False]])