## PyTorch Tensor Operations

In [1]:
# import
import torch

### Resizing Tensor

In [2]:
tensor = torch.ones(2, 2)
print(tensor)

tensor([[1., 1.],
        [1., 1.]])


In [3]:
tensor.size()

torch.Size([2, 2])

In [4]:
tensor.view(4) # resize

tensor([1., 1., 1., 1.])

In [5]:
tensor.view(4).size()

torch.Size([4])

### Element-wise Addition

In [6]:
a = torch.ones(2, 2)
b = torch.ones(2, 2)
a, b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [7]:
# element-wise addition
c = a + b
c

tensor([[2., 2.],
        [2., 2.]])

In [8]:
# element-wise addition
c = torch.add(a, b)
c

tensor([[2., 2.],
        [2., 2.]])

In [9]:
# not in-place addition
print('Old c tensor')
print(c)

c.add(a)

print('-'*10)
print('New c tensor')
print(c)

Old c tensor
tensor([[2., 2.],
        [2., 2.]])
----------
New c tensor
tensor([[2., 2.],
        [2., 2.]])


In [10]:
# in-place addition
print('Old c tensor')
print(c)

c.add_(a)

print('-'*10)
print('New c tensor')
print(c)

Old c tensor
tensor([[2., 2.],
        [2., 2.]])
----------
New c tensor
tensor([[3., 3.],
        [3., 3.]])


### Element-wise Subtraction

In [11]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [12]:
a - b

tensor([[0., 0.],
        [0., 0.]])

In [13]:
# not in-place
print(a.sub(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [14]:
# in-place
print(a.sub_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


### Element-wise Multiplication

In [15]:
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [16]:
a * b

tensor([[0., 0.],
        [0., 0.]])

In [17]:
# not in-place
print(a.mul(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [18]:
# in-place
print(a.mul_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


### Element-wise Division

In [19]:
a = torch.ones(2, 2)
b = torch.zeros(2, 2)

In [20]:
b / a

tensor([[0., 0.],
        [0., 0.]])

In [21]:
torch.div(b, a)

tensor([[0., 0.],
        [0., 0.]])

In [22]:
# not in-place
b.div(a)

tensor([[0., 0.],
        [0., 0.]])

In [23]:
b.div_(a)

tensor([[0., 0.],
        [0., 0.]])

### Tensor Mean
* 1+2+3+4+5+6+7+8+9+10 = 55
* mean = 55/10 = 5.5

In [24]:
a = torch.Tensor(range(1, 11))
a.size()

torch.Size([10])

In [25]:
a.mean(dim=0) # 0 means one dimension.

tensor(5.5000)

In [26]:
b = torch.Tensor([range(1, 11), range(1, 11)])

In [27]:
b.size()

torch.Size([2, 10])

In [28]:
b.mean(0)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
b.mean(1)

tensor([5.5000, 5.5000])

### Tensor Standard Deviation

In [30]:
a = torch.Tensor(range(1, 11))
a.std(dim=0)

tensor(3.0277)